baseURL = "https://rats-make-robot.github.io"
title = "RATS"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 5 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true



[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = ""
  author = ""
  favicon = ""  site_logo = "img/logo.svg"
  description = "명지대학교 유일무이 로봇동아리 RATS"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3


[[params.ananke_socials]]
name = "github"
url = "https://github.com/RATS-make-robot"

[[params.ananke_socials]]
name = "facebook"
url = "https://ko-kr.facebook.com/RATSMJU/"
