baseURL : https://join.mju-rats.com/
title : "RATS 홍보페이지"

theme : "toha"
languageCode : en-us
# Control TOC depth

# Force a locale to be use, really useful to develop the application ! Should be commented in production, the "weight" should rocks.
DefaultContentLanguage: en

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - JSON

# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  # Background image of the landing page
  background: /images/site/background.jpg

  # Provide logos for your site. The inverted logo will be used in the initial
  # transparent navbar and the main logo will be used in the non-transparent navbar.
  logo:
    main: /images/site/main-logo.png
    inverted: /images/site/inverted-logo.png
    favicon: /images/site/favicon.png

  # GitHub repo of your site
  gitRepo: https://github.com/RATS-make-robot/RATS-make-robot.github.io
  # Default branch of your Git repo
  gitBranch: toha

  # Configure the number of section title visible in the top navbar
  topNavbar:
    maxVisibleSections: 6

  # Configure various features of this theme
  features:
    # Enable and configure portfolio
    portfolio:
      enable: true
    # Enable and configure blog posts
    blog:
      enable: false
      # Share post on different social media
      shareButtons:
        facebook: true
        twitter: true
        linkedin: true
        reddit: true
        whatsapp: true
        email: true
        # tumblr: true
        # pocket: true
        # diaspora: true
        # mastodon: true
  customMenus:
  - name: 인스타그램 #커뮤니티
    url: https://www.instagram.com/mjurats/ #https://community.mju-rats.com/
    hideFromNavbar: false
  # specify whether to show the menu item in footer or not.
  # if you set it to true, make sure you have set `footer.navigation.customMenus: true` in your config.yaml
    showOnFooter: true
  - name: 2024 신입 부원 신청(3월 중 open)
    url: https://forms.gle/S7hWkCaxsYgQtZVi8
    hideFromNavbar: false
    showOnFooter: true


    # Enable & configure "Notes" features
    notes:
      enable: false

    # Enable comment feature. There, should be only one of them.
    comment:
      enable: false
      disqus:
        shortName: toha-example-site
      # valine:
      #   appId: HTV6askWxVo3vOxlqjjaq2hd-MsYXbMMI
      #   appKey: pVrT3C85KGIuk27t07eh6bUC
      #   avatar: retro
      #   placeholder: Share your thought.
      #   lang: en
      #   recordIP: true
      #   enableQQ: true
      # utteranc:
      #   repo: github.com/hugo-toha/hugo-toha.github.io
      #   issueTerm: title
      #   theme: github-light


  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Show tags under the post title
  enableTags: true

  # If you want to use different country flag for a language, specify them here.
  # flagOverwrites:
  # - languageCode: en
  #   countryCode: us

  # Provide footer configuration.
  footer:
    enable: true
    # You can provide your custom footer template using this option.
    # Put your template in "layouts/partials" folder of your repo.
    template: footer.html
    # Show/hide navigation in the footer. Default is "true".
    navigation:
      enable: true
      # show custom menus in the footer
      customMenus: true
    # Show/hide "Contact Me" section in the footer. Default is "true".
    contactMe:
      enable: true
    # Show/hide credentials section in the footer. Default is "true".
    credentials:
      enable: true

    # Show/hide newsletter section in the footer. Default is "true".
    # Currently, it supports "mailchimp".
    newsletter:
      enable: false
      provider: mailchimp
      mailchimpURL: https://github.us1.list-manage.com/subscribe/post?u=19de52a4603135aae97163fd8&amp;id=094a24c76e

    # Show/hide disclaimer notice in the footer. Default is "false".
    disclaimer:
      enable: true
