baseURL = "https://rats-make-robot.github.io"
title = "RATS"

theme = "hugo-universal-theme"
themesDir = "./themes"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "en"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

# number of words of summarized post content (default 70)
summaryLength = 70

# Define the number of posts per page
paginate = 10

[menu]


# Main menu
[[menu.main]]
    name       = "Home"
    identifier = "menu.home"
    url        = "/"
    weight     = 1



[[menu.main]]
    name       = "Activity"
    identifier = "menu.Activity"
    url        = "/activity"
    weight     = 3


[[menu.main]]
    name       = "history"
    identifier = "section.history"
    url        = "/history"
    weight     = 2
    post       = 2


[[menu.main]]
    name       = "project"
    identifier = "menu.project"
    url        = "/project/"
    weight     = 5
    post       = 4


[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/contact/"
    weight     = 6


[[menu.main]]
    identifier = "menu.sites"
    name       = "sites"
    url        = "/sites/"
    weight     = 7

[[menu.main]]
    name       = "Community"
    url        = "https://community.mju-rats.com/"
    weight     = 1
    parent     = "menu.sites"
    
[[menu.main]]
    name       = "Cloud"
    url        = "https://cloud.mju-rats.com/"
    weight     = 2
    parent     = "menu.sites"

[[menu.main]]
    name       = "github"
    url        = "https://github.com/RATS-make-robot"
    weight     = 3
    parent     = "menu.sites"

[[menu.main]]
    name       = "facebook"
    url        = "https://ko-kr.facebook.com/RATSMJU/"
    weight     = 4
    parent     = "menu.sites"


[params]
    viewMorePostLink = "/project/"
    author = "RATS"
    defaultKeywords = ["RATS", "robot", "coding"]
    mainSections = ["project"]
    defaultDescription = "명지대학교 로봇동아리 레츠"

    # Social media
    facebook_site = "" # the Facebook handle of your site ('https://www.facebook.com/HANDLE')
    twitter_site = "GoHugoIO" # the Twitter handle of your site (without the '@')
    default_sharing_image = "img/sharing-default.png"

    # Google Maps widget: If `googleMapsApiKey` is not set, no key will be passed to Google (which likely results in a broken map widget).
    enableGoogleMaps = true
    googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"

    latitude = "-12.043333"
    longitude = "-77.028333"

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "blue"


    formspree_action = ""
    contact_form_ajax = false

    enableRecaptchaInContactForm = false
    googleRecaptchaKey = "site_key_for_google_recaptcha"

    about_us = "<p>명지대학교 로봇 동아리 RATS</p>"
    copyright = "Copyright (c) 2022, YourCompany; all rights reserved."

    # Format dates with Go's time formatting
    date_format = "January 2, 2006"

    disabled_logo = false
    logo_text = "RATS"

    logo = "img/logo.png"
    logo_small = "img/logo_small.png"
    contact_url = "/contact"
    address = """<p class="text-uppercase"><strong>명지대학교 RATS</strong>
        <br>13/25 용인시 처인구
        <br>명지 대학교 1234
        <br>5층 2호
        <br>RATS 동아리방 주소
        <br>
        <strong>대한 민국</strong>
      </p>
      """

[permalinks]
    blog = "/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = false

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = false
    tags = false
    search = false


[params.features]
    enable = true
    cols = 3 # Default: 3, Available values 2,3,4,6
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more information take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more information take a look at the README.
    title = "Testimonials"
    subtitle = "인용구 부분 사용 안함."

[params.see_more]
    enable = true
    icon = "far fa-file-alt"
    title = "가입 하고 싶죠?"
    subtitle = "축하 합니다 당신은 당장 가입 할 수 있습니다."
    link_url = "https://www.google.com/"
    link_text = "당장 가입하기"

[params.clients]
    enable = false
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more information take a look at the README.
    title = "Our Clients"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "우리 동아리에서는"
    subtitle = "모든종류의 개발 모든 종류의 제작을 합니다."
    hide_summary = false

[params.footer.recent_posts]
    enable = false

[taxonomies]
  category = "categories"
  tag = "tags"
  author = "authors"
