# action 이름. 원하는대로 정하면 된다. 
name: deploy ghpage

# on: 뒤에오는 event가 발생하면 action이 실행된다. 아래는 master branch에 push 나 pull request가 발생하면 action이 실행되는 코드이다. 보통 그냥 두면 된다. 
on:
  push:
    branches: [ toha ]
  pull_request:
    branches: [ toha ]

# jobs은 실행될 action을 포함하고 있다.  
jobs:
  
  build:
    runs-on: ubuntu-22.04
    #steps는 명령어 들이다. 
    # uses는 이미 만들어진 action을 사용하는 것, run은 명령어를 실행하는 것이다. 
    steps: 
    
    #1. 가상머신으로 checkout
    - uses: actions/checkout@v4
      with:
        submodules: true  # Fetch Hugo themes (true OR recursive)
        fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod


    #4. Hugo 설치 
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

        
    #5. build (public 폴더에 저장 된다.)
    - name: Build Hugo Site
      run: hugo --minify && cd public && pwd
       # minify는 압축시키는 것을 의미한다. 
    
    #6.Deploy 배포: git token이 필요하다. gh-pages로 publish하는 것 잊지 말자 
    #public 폴더를 github page의 gh-pages 브챈치에 배포한다는 의미이다. 
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.mabangkey }}
        publish_branch: gh-pages
        publish_dir: ./public
        cname: join.mju-rats.com
        
  download:
    needs: build
    runs-on: ubuntu-latest

    steps:
      # 1. Download the artifact
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: hugo-site
          path: ./downloaded-site
